# Prometheus configuration for CollabSpace
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'collabspace-monitor'

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CollabSpace Backend (Spring Boot)
  - job_name: 'collabspace-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend-java:8080']
    scrape_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'backend-java:8080'

  # AI Service (Python Flask)
  - job_name: 'collabspace-ai'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['ai-service:5000']

  # Real-time Engine (Node.js)
  - job_name: 'collabspace-websocket'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['realtime-engine:3001']

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
